# lab 1

this is my first lab

In [3]:
import pandas as pd 

covid_data = pd.read_csv("s3://ia-340-fa25-ibrahim/data.csv")
covid_data.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,14/12/2020,14,12,2020,746,6,Afghanistan,AF,AFG,38041757.0,Asia,9.013779
1,13/12/2020,13,12,2020,298,9,Afghanistan,AF,AFG,38041757.0,Asia,7.052776
2,12/12/2020,12,12,2020,113,11,Afghanistan,AF,AFG,38041757.0,Asia,6.868768
3,11/12/2020,11,12,2020,63,10,Afghanistan,AF,AFG,38041757.0,Asia,7.134266
4,10/12/2020,10,12,2020,202,16,Afghanistan,AF,AFG,38041757.0,Asia,6.968658

In [4]:
crime_data = pd.read_csv("s3://ia-340-fa25-ibrahim/SPD_Crime_Data__2008-Present.csv")
crime_data.head()

,Report Number,Report DateTime,Offense ID,Offense Date,NIBRS Group AB,NIBRS Crime Against Category,Offense Sub Category,Shooting Type Group,Block Address,Latitude,Longitude,Beat,Precinct,Sector,Neighborhood,Reporting Area,Offense Category,NIBRS Offense Code Description,NIBRS_offense_code
0,2013-217957,06/22/2013 09:29:00 PM,7686115988,06/22/2013 09:29:00 PM,A,PERSON,AGGRAVATED ASSAULT,-,-,-1.0,-1.0,F1,Southwest,F,-,1678,VIOLENT CRIME,Aggravated Assault,13A
1,2009-237520,07/08/2009 05:54:00 PM,7641304087,07/08/2009 07:00:00 AM,A,PROPERTY,LARCENY-THEFT,-,11XX BLOCK OF WESTERN AVE,47.60530026,-122.338327485671,K1,West,K,-,469,PROPERTY CRIME,Theft of Motor Vehicle Parts or Accessories,23G
2,2015-079168,03/10/2015 02:06:00 PM,7680665743,03/10/2015 01:11:00 PM,A,PROPERTY,LARCENY-THEFT,-,44XX BLOCK OF 4TH AVE S,47.56380429,-122.329368514925,O2,South,O,-,11067,PROPERTY CRIME,Shoplifting,23C
3,2022-163752,06/26/2022 08:43:59 PM,34519102321,06/26/2022 06:16:00 PM,B,SOCIETY,TRESPASS,-,REDACTED,REDACTED,REDACTED,N2,North,N,NORTHGATE,REDACTED,ALL OTHER,Trespass of Real,90J
4,2017-268444,07/23/2017 12:41:00 AM,7637289721,07/22/2017 11:55:00 PM,A,PERSON,ASSAULT OFFENSES,-,1XX BLOCK OF YESLER WAY,47.60172211,-122.334038699999,K1,West,K,DOWNTOWN COMMERCIAL,12793,ALL OTHER,Simple Assault,13B